package no.nav.klage.kaka.domain

enum class Vedtaksinstansgruppe(val id: Int) {
    AKERSHUS(0),
    OSLO(1),
    VESTLAND(2),
    ROGALAND(3),
    TROENDELAG(4),
    INNLANDET(5),
    AGDER(6),
    OESTFOLD(7),
    MOERE_OG_ROMSDAL(8),
    BUSKERUD(9),
    VESTFOLD(10),
    NORDLAND(11),
    TELEMARK(12),
    TROMS(13),
    FINNMARK(14),
    NAV_OEKONOMI_STOENAD(15),
    NAV_ARBEID_OG_YTELSER(16),
    NAV_KONTROLL_FORVALTNING(17),
    NAV_HJELPEMIDDELSENTRAL(18),
    NAV_FAMILIE_OG_PENSJONSYTELSER(19),
    UNKNOWN(999),
}

val vedtaksinstansgruppeMap = mapOf(
    "02" to Vedtaksinstansgruppe.AKERSHUS,
    "03" to Vedtaksinstansgruppe.OSLO,
    "46" to Vedtaksinstansgruppe.VESTLAND,
    "12" to Vedtaksinstansgruppe.VESTLAND,
    "14" to Vedtaksinstansgruppe.VESTLAND,
    "13" to Vedtaksinstansgruppe.VESTLAND,
    "11" to Vedtaksinstansgruppe.ROGALAND,
    "50" to Vedtaksinstansgruppe.TROENDELAG,
    "16" to Vedtaksinstansgruppe.TROENDELAG,
    "17" to Vedtaksinstansgruppe.TROENDELAG,
    "57" to Vedtaksinstansgruppe.TROENDELAG,
    "34" to Vedtaksinstansgruppe.INNLANDET,
    "04" to Vedtaksinstansgruppe.INNLANDET,
    "05" to Vedtaksinstansgruppe.INNLANDET,
    "09" to Vedtaksinstansgruppe.AGDER,
    "10" to Vedtaksinstansgruppe.AGDER,
    "01" to Vedtaksinstansgruppe.OESTFOLD,
    "15" to Vedtaksinstansgruppe.MOERE_OG_ROMSDAL,
    "06" to Vedtaksinstansgruppe.BUSKERUD,
    "07" to Vedtaksinstansgruppe.VESTFOLD,
    "53" to Vedtaksinstansgruppe.VESTFOLD,
    "18" to Vedtaksinstansgruppe.NORDLAND,
    "08" to Vedtaksinstansgruppe.TELEMARK,
    "19" to Vedtaksinstansgruppe.TROMS,
    "20" to Vedtaksinstansgruppe.FINNMARK,
    "41" to Vedtaksinstansgruppe.NAV_OEKONOMI_STOENAD,
    "44" to Vedtaksinstansgruppe.NAV_ARBEID_OG_YTELSER,
    "45" to Vedtaksinstansgruppe.NAV_KONTROLL_FORVALTNING,
    "47" to Vedtaksinstansgruppe.NAV_HJELPEMIDDELSENTRAL,
    "48" to Vedtaksinstansgruppe.NAV_FAMILIE_OG_PENSJONSYTELSER,
    "42" to Vedtaksinstansgruppe.UNKNOWN,
    "21" to Vedtaksinstansgruppe.UNKNOWN,
    "00" to Vedtaksinstansgruppe.UNKNOWN,
)