TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

AXSYS_URL: https://api-gw-q1.oera.no/axsys/api/v2
AXSYS_CLUSTER: dev-fss
AXSYS_NAMESPACE: org
AXSYS_APP: axsys

PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io/graphql
PDL_SCOPE: dev-fss.pdl.pdl-api

EREG_URL: https://api-gw-q1.oera.no/ereg-services/api

NORG2_BASE_URL: https://norg2.dev-fss-pub.nais.io/norg2/api/v1

KAKA_VERSION_2_DATE: 2022-12-14
MIGRATE_CRON: 0 0 0 14 DEC *