TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b

AXSYS_URL: https://api-gw.oera.no/axsys/api/v2
AXSYS_CLUSTER: prod-fss
AXSYS_NAMESPACE: org
AXSYS_APP: axsys

PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io/graphql
PDL_SCOPE: prod-fss.pdl.pdl-api

EREG_URL: https://api-gw.oera.no/ereg-services/api

NORG2_BASE_URL: https://norg2.prod-fss-pub.nais.io/norg2/api/v1

KAKA_VERSION_2_DATE: 2023-01-01
MIGRATE_CRON: 0 0 0 1 JAN ? 2023