TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

AXSYS_URL: https://api-gw-q1.oera.no/axsys/api/v2
AXSYS_CLUSTER: dev-fss
AXSYS_NAMESPACE: org
AXSYS_APP: axsys

ROLE_KAKA_KVALITETSVURDERING: a4dbd743-5adb-45c8-8918-59c2c6e8e3f2
ROLE_KLAGE_LEDER: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
ROLE_KAKA_KVALITETSTILBAKEMELDINGER: ef9eaacb-a19d-4d13-bfc5-930e4fb217cd
ROLE_KLAGE_EGEN_ANSATT: 011af9b0-792d-4d2c-a2eb-9a59fc095002
ROLE_KLAGE_FORTROLIG: 2980c598-8af7-473f-b7d1-233f785d7001
ROLE_KLAGE_STRENGT_FORTROLIG: de92036b-c350-471c-9249-753f36acd24d
ROLE_KAKA_TOTALSTATISTIKK: 82c229e8-0ff7-41cb-a34d-92872afb84c5
ROLE_KAKA_LEDERSTATISTIKK: 159c9814-4056-4809-8c90-d75e71ac0893
ROLE_ADMIN: a9f5ef81-4e81-42e8-b368-0273071b64b9

PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io/graphql
PDL_SCOPE: dev-fss.pdl.pdl-api

EREG_URL: https://api-gw-q1.oera.no/ereg/api