TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

KAKA_VERSION_2_DATE: 2022-12-20

KAKA_VERSION_3_DATE: 2025-11-11

spring:
  datasource:
    hikari:
      maximum-pool-size: 5

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true