NAIS_DATABASE_KAKA_API_KAKA_API_HOST: localhost
NAIS_DATABASE_KAKA_API_KAKA_API_PORT: 5432
NAIS_DATABASE_KAKA_API_KAKA_API_DATABASE: kaka-api
NAIS_DATABASE_KAKA_API_KAKA_API_USERNAME: kaka
NAIS_DATABASE_KAKA_API_KAKA_API_PASSWORD: kaka