NAIS_DATABASE_KAKA_API_KAKA_API_HOST: localhost
NAIS_DATABASE_KAKA_API_KAKA_API_PORT: 5432
NAIS_DATABASE_KAKA_API_KAKA_API_DATABASE: kaka-api
NAIS_DATABASE_KAKA_API_KAKA_API_USERNAME: kaka
NAIS_DATABASE_KAKA_API_KAKA_API_PASSWORD: kaka

AZURE_APP_WELL_KNOWN_URL: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
