package no.nav.klage.kaka.api.view

import no.nav.klage.kaka.domain.KvalitetsvurderingV1

data class KvalitetsvurderingV1Input (
    val klageforberedelsenRadioValg: KvalitetsvurderingV1.RadioValg?,
    val sakensDokumenter: Boolean?,
    val oversittetKlagefristIkkeKommentert: Boolean?,
    val klagerensRelevanteAnfoerslerIkkeKommentert: Boolean?,
    val begrunnelseForHvorforAvslagOpprettholdes: Boolean?,
    val konklusjonen: Boolean?,
    val oversendelsesbrevetsInnholdIkkeISamsvarMedTema: Boolean?,
    val utredningenRadioValg: KvalitetsvurderingV1.RadioValg?,
    val utredningenAvMedisinskeForhold: Boolean?,
    val utredningenAvMedisinskeForholdText: String?,
    val utredningenAvInntektsforhold: Boolean?,
    val utredningenAvInntektsforholdText: String?,
    val utredningenAvArbeid: Boolean?,
    val utredningenAvArbeidText: String?,
    val arbeidsrettetBrukeroppfoelging: Boolean?,
    val arbeidsrettetBrukeroppfoelgingText: String?,
    val utredningenAvAndreAktuelleForholdISaken: Boolean?,
    val utredningenAvAndreAktuelleForholdISakenText: String?,
    val utredningenAvEoesProblematikk: Boolean?,
    val utredningenAvEoesProblematikkText: String?,
    val veiledningFraNav: Boolean?,
    val veiledningFraNavText: String?,
    val brukAvRaadgivendeLegeRadioValg: KvalitetsvurderingV1.RadioValgRaadgivendeLege?,
    val raadgivendeLegeErIkkeBrukt: Boolean?,
    val raadgivendeLegeErBruktFeilSpoersmaal: Boolean?,
    val raadgivendeLegeHarUttaltSegUtoverTrygdemedisin: Boolean?,
    val raadgivendeLegeErBruktMangelfullDokumentasjon: Boolean?,
    val vedtaketRadioValg: KvalitetsvurderingV1.RadioValg?,
    val detErIkkeBruktRiktigHjemmel: Boolean?,
    val innholdetIRettsregleneErIkkeTilstrekkeligBeskrevet: Boolean?,
    val rettsregelenErBenyttetFeil: Boolean?,
    val vurderingAvFaktumErMangelfull: Boolean?,
    val detErFeilIKonkretRettsanvendelse: Boolean?,
    val begrunnelsenErIkkeKonkretOgIndividuell: Boolean?,
    val spraaketErIkkeTydelig: Boolean?,
    val nyeOpplysningerMottatt: Boolean?,
    val brukIOpplaering: Boolean?,
    val brukIOpplaeringText: String?,
    val betydeligAvvik: Boolean?,
    val betydeligAvvikText: String?,
)