ingress:
  - https://kaka-api.dev.nav.no
externalHosts:
  - host: login.microsoftonline.com
springProfile: dev-gcp
tenant: trygdeetaten.no
ROLE_KAKA_SAKSBEHANDLER: a4dbd743-5adb-45c8-8918-59c2c6e8e3f2
ROLE_KLAGE_LEDER: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
ROLE_VEDTAKSINSTANS_LEDER: ef9eaacb-a19d-4d13-bfc5-930e4fb217cd
ROLE_KLAGE_STRENGT_FORTROLIG: de92036b-c350-471c-9249-753f36acd24d
db_tier: db-custom-1-3840
db_size: 10
db_ha: true
envs:
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx2048m"