ingress:
  - https://kaka-api.dev.nav.no
externalHosts:
  - host: login.microsoftonline.com
  - host: pdl-api.dev-fss-pub.nais.io
  - host: api-gw-q1.oera.no
  - host: norg2.dev-fss-pub.nais.io
springProfile: dev-gcp
tenant: trygdeetaten.no
kafka_pool: nav-dev
db_tier: db-custom-1-3840
db_size: 10
db_ha: true
envs:
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx2048m"

groups:
  - name: ROLE_KAKA_KVALITETSVURDERING
    value: a4dbd743-5adb-45c8-8918-59c2c6e8e3f2
  - name: ROLE_KLAGE_LEDER
    value: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
  - name: ROLE_KAKA_KVALITETSTILBAKEMELDINGER
    value: ef9eaacb-a19d-4d13-bfc5-930e4fb217cd
  - name: ROLE_KLAGE_EGEN_ANSATT
    value: 011af9b0-792d-4d2c-a2eb-9a59fc095002
  - name: ROLE_KLAGE_FORTROLIG
    value: 2980c598-8af7-473f-b7d1-233f785d7001
  - name: ROLE_KLAGE_STRENGT_FORTROLIG
    value: de92036b-c350-471c-9249-753f36acd24d
  - name: ROLE_KAKA_TOTALSTATISTIKK
    value: 82c229e8-0ff7-41cb-a34d-92872afb84c5
  - name: ROLE_KAKA_LEDERSTATISTIKK
    value: 159c9814-4056-4809-8c90-d75e71ac0893
  - name: ROLE_ADMIN
    value: a9f5ef81-4e81-42e8-b368-0273071b64b9