ingresses:
  - https://kaka-api.dev.nav.no
  - https://kaka-api.intern.dev.nav.no
externalHosts:
  - host: login.microsoftonline.com
  - host: pdl-api.dev-fss-pub.nais.io
  - host: api-gw-q1.oera.no
  - host: norg2.dev-fss-pub.nais.io
springProfile: dev-gcp
tenant: trygdeetaten.no
kafka_pool: nav-dev
db_tier: db-custom-1-3840
db_size: 10
db_ha: true
envs:
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx2048m"

groups:
  - name: KAKA_KVALITETSVURDERING_ROLE_ID
    value: a4dbd743-5adb-45c8-8918-59c2c6e8e3f2
    #TODO: Undersøk behov.
  - name: ROLE_KLAGE_LEDER
    value: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
  - name: KAKA_KVALITETSTILBAKEMELDING_ROLE_ID
    value: ef9eaacb-a19d-4d13-bfc5-930e4fb217cd
  - name: EGEN_ANSATT_ROLE_ID
    value: dbe4ad45-320b-4e9a-aaa1-73cca4ee124d
  - name: FORTROLIG_ROLE_ID
    value: ea930b6b-9397-44d9-b9e6-f4cf527a632a
  - name: STRENGT_FORTROLIG_ROLE_ID
    value: 5ef775f2-61f8-4283-bf3d-8d03f428aa14
  - name: KAKA_TOTALSTATISTIKK_ROLE_ID
    value: 82c229e8-0ff7-41cb-a34d-92872afb84c5
  - name: KAKA_LEDERSTATISTIKK_ROLE_ID
    value: 159c9814-4056-4809-8c90-d75e71ac0893
  - name: ADMIN_ROLE_ID
    value: a9f5ef81-4e81-42e8-b368-0273071b64b9