package no.nav.klage.kaka.domain.kodeverk

enum class Role {
    KAKA_KVALITETSVURDERING,
    KAKA_KVALITETSTILBAKEMELDINGER,
    KAKA_TOTALSTATISTIKK,
    KAKA_LEDERSTATISTIKK,

    EGEN_ANSATT,
    FORTROLIG,
    STRENGT_FORTROLIG,

    KAKA_EXCEL_UTTREKK_MED_FRITEKST,
    KAKA_EXCEL_UTTREKK_UTEN_FRITEKST,

    KAKA_ADMIN,

    //Old roles
    ROLE_KLAGE_LEDER,
}