CREATE INDEX rkv2vbf_kvalitestvurdering_v2_ix ON kaka.registreringshjemmel_kvalitetsvurdering_v2_vedtaket_brukt_feil_ (kvalitetsvurdering_v2_id);
CREATE INDEX rkv2vfk_kvalitestvurdering_v2_ix ON kaka.registreringshjemmel_kvalitetsvurdering_v2_vedtaket_feil_konkre (kvalitetsvurdering_v2_id);
CREATE INDEX rkv2vii_kvalitestvurdering_v2_ix ON kaka.registreringshjemmel_kvalitetsvurdering_v2_vedtaket_innholdet_i (kvalitetsvurdering_v2_id);
CREATE INDEX rkv2vl_kvalitestvurdering_v2_ix ON kaka.registreringshjemmel_kvalitetsvurdering_v2_vedtaket_lovbestemme (kvalitetsvurdering_v2_id);
CREATE INDEX rkv2vahl_kvalitestvurdering_v2_ix ON kaka.r_k_v2_vedtaket_arheiv_hjemler_list (kvalitetsvurdering_v2_id);
CREATE INDEX rkv2vbhl_kvalitestvurdering_v2_ix ON kaka.r_k_v2_vedtaket_bfh_hjemler_list (kvalitetsvurdering_v2_id);